version: "3"

services:
  mariadb:
    image: mariadb:10.3
    restart: always
    environment:
     MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
 
volumes:
  mariadb_data:
    driver: local
